[tool.poetry]
name = "faithfulness"
version = "0.1.0"
description = ""
authors = ["Joakim Edin <je@corti.ai>", "Casper Christensen <clu@corti.ai>", "Andreas G. Motzfeldt <amo@corti.ai>"]
readme = "README.md"

packages = [
    {include="aopc"}
]

[tool.poetry.dependencies]
python = "^3.10"
torch = "<2.3.0"
transformers = "^4.41.2"
datasets = "^2.20.0"
loguru = "^0.7.3"
numba = "^0.60.0"
numpy = "^2.0.1"


[tool.poetry.group.feat-attr]
optional = true

[tool.poetry.group.feat-attr.dependencies]
captum = "^0.7.0"


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.8"
ipython = "8.25.0"
ipykernel = "^6.29.4"
rich = "^13.7.1"
matplotlib = "^3.9.0"
seaborn = "^0.13.2"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-lazy-fixture="^0.6.3"
pytest-cov = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
