[tool.poetry]
name = "naopc"
version = "0.1.0"
description = ""
authors = ["Joakim Edin <je@corti.ai>", "Casper Christensen <clu@corti.ai>", "Andreas G. Motzfeldt <amo@corti.ai>"]
readme = "README.md"

package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
aopc = {path = "aopc", develop = true}


[tool.poetry.group.feat-attr]
optional = true

[tool.poetry.group.feat-attr.dependencies]
captum = "^0.7.0"


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.8"
ipython = "8.25.0"
ipykernel = "^6.29.4"
rich = "^13.7.1"
matplotlib = "^3.9.0"
seaborn = "^0.13.2"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-cov = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
